### ISSUE TITLE
ResourceOf

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#127]
Implement this, with `ResourceOf` from cactoos:
```java
final Producer<String, String> producer =
        new KfProducer<>(
          new KfProducerSettings<String, String>(
            new ResourceOf("settings.xml")
          )
        );
```
@h1alexbel what do you think?

**Comment by h1alexbel** [comment]
@l3r8yJ cool, go ahead

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#142](https://github.com/eo-cqrs/eo-kafka/issues/142) is still not solved.
