### ISSUE TITLE
each kafka setting/property = object

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#134]

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#141](https://github.com/eo-cqrs/eo-kafka/issues/141) is still not solved.

**Comment by l3r8yJ** [comment]
@h1alexbel can we do pre-release `0.0.2`?

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#150](https://github.com/eo-cqrs/eo-kafka/issues/150) is still not solved; solved: [#141](https://github.com/eo-cqrs/eo-kafka/issues/141), [#151](https://github.com/eo-cqrs/eo-kafka/issues/151).

**Comment by 0pdd** [comment]
@h1alexbel all 3 puzzles are solved here: [#141](https://github.com/eo-cqrs/eo-kafka/issues/141), [#150](https://github.com/eo-cqrs/eo-kafka/issues/150), [#151](https://github.com/eo-cqrs/eo-kafka/issues/151).
