### ISSUE TITLE
Rename ParamsAttribute

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#144]
better name will be `ParamsAttribute` –> `KfAttr`
@h1alexbel wdyt

**Comment by h1alexbel** [comment]
@l3r8yJ It's better to name interfaces without any prefixes, so I think `ParamsAttribute` is ok, maybe can be cut to `ParamsAttr`

**Comment by l3r8yJ** [comment]
@h1alexbel yes, i like your suggestion more
