### ISSUE TITLE
Producer/Consumer settings impl

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#147]
To be honest, I didn't like the way our `Consumer/ProducerSettings` build `consumer` or `producer`, with this implementation we have big problems scaling or adding new properties to `Consumer/ProducerSettings`.
```java
  @Override
  public KafkaProducer<K, X> producer() {
    final Map<String, Object> config = new HashMap<>(3);
    config.put(
      "bootstrap.servers",
      new TextXpath(this.settings, "//bootstrapServers")
        .toString()
    );
    config.put(
      "key.serializer",
      new TextXpath(this.settings, "//keySerializer")
        .toString()
    );
    config.put(
      "value.serializer",
      new TextXpath(this.settings, "//valueSerializer")
        .toString()
    );
    return new KafkaProducer<>(config);
  }
```

Suppose I want to add a new property - `ssl.key.password`.
What should I do with it? 
I should create a new class with an external name `SslKeyPassword` and add some code to that method:
```java
config.put(
  "ssl.key.password",
  new TextXpath(this.settings, "//SslKeyPassword").toString()
);
```
I think the right way to implement this should look like this:
```java
  @Override
  public KafkaProducer<K, X> producer() {
    final Map<String, Object> config = this.params.all()
      .stream()
      .collect(
        Collectors.toMap(
          ParamsAttr::name,
          param -> 
            new TextXpath(
              new XMLDocument(this.params.asXml()), 
              param.asXpath()
            )
          ).toString()
      );
    return new KafkaProducer<>(config);
  }
```

to do this, we just need to implement the `asXpath` method and refactor `AttrEnvelope#nameInCamelCase()` a bit

@h1alexbel wdyt

**Comment by l3r8yJ** [comment]
And I have another question, is the configuration through `.xml` a necessary item for our project?

**Comment by h1alexbel** [comment]
@l3r8yJ I like your suggestion. And XML is not necessary, but simplifies the construction of consumers and producers

**Comment by h1alexbel** [comment]
I agree with you, that code is not extendable

**Comment by l3r8yJ** [comment]
@h1alexbel then I have a theoretically good solution, i'll send a pr later

**Comment by 0pdd** [comment]
@l3r8yJ 3 puzzles [#154](https://github.com/eo-cqrs/eo-kafka/issues/154), [#155](https://github.com/eo-cqrs/eo-kafka/issues/155), [#156](https://github.com/eo-cqrs/eo-kafka/issues/156) are still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ 4 puzzles [#155](https://github.com/eo-cqrs/eo-kafka/issues/155), [#162](https://github.com/eo-cqrs/eo-kafka/issues/162), [#163](https://github.com/eo-cqrs/eo-kafka/issues/163), [#164](https://github.com/eo-cqrs/eo-kafka/issues/164) are still not solved; solved: [#154](https://github.com/eo-cqrs/eo-kafka/issues/154), [#156](https://github.com/eo-cqrs/eo-kafka/issues/156).

**Comment by 0pdd** [comment]
@l3r8yJ 3 puzzles [#155](https://github.com/eo-cqrs/eo-kafka/issues/155), [#162](https://github.com/eo-cqrs/eo-kafka/issues/162), [#164](https://github.com/eo-cqrs/eo-kafka/issues/164) are still not solved; solved: [#154](https://github.com/eo-cqrs/eo-kafka/issues/154), [#156](https://github.com/eo-cqrs/eo-kafka/issues/156), [#163](https://github.com/eo-cqrs/eo-kafka/issues/163).

**Comment by 0pdd** [comment]
@l3r8yJ 2 puzzles [#155](https://github.com/eo-cqrs/eo-kafka/issues/155), [#162](https://github.com/eo-cqrs/eo-kafka/issues/162) are still not solved; solved: [#154](https://github.com/eo-cqrs/eo-kafka/issues/154), [#156](https://github.com/eo-cqrs/eo-kafka/issues/156), [#163](https://github.com/eo-cqrs/eo-kafka/issues/163), [#164](https://github.com/eo-cqrs/eo-kafka/issues/164).

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#155](https://github.com/eo-cqrs/eo-kafka/issues/155) is still not solved; solved: [#154](https://github.com/eo-cqrs/eo-kafka/issues/154), [#156](https://github.com/eo-cqrs/eo-kafka/issues/156), [#162](https://github.com/eo-cqrs/eo-kafka/issues/162), [#163](https://github.com/eo-cqrs/eo-kafka/issues/163), [#164](https://github.com/eo-cqrs/eo-kafka/issues/164).

**Comment by h1alexbel** [comment]
@l3r8yJ seems that this issue was completed. Can I close this one?

**Comment by l3r8yJ** [comment]
@h1alexbel cheers!
