### ISSUE TITLE
Integrate checkstyle to project

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#149]
It would be nice if we had examples of good formatting for checkstyle settings

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#231](https://github.com/eo-cqrs/eo-kafka/issues/231) is still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#231](https://github.com/eo-cqrs/eo-kafka/issues/231) is solved here.
