### ISSUE TITLE
StringsInCamelCase.java:33-36: Transfer this...

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#151]
The puzzle `141-51feecdd` from #141 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/27fa4414b318a712e92965002d05bb91f5404e41/src/main/java/io/github/eocqrs/kafka/xml/StringsInCamelCase.java#L33-L36

The puzzle was created by Ivan on 21-Mar-23. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
https://github.com/yegor256/cactoos/pull/1678

cc:
@l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel forgot to say, i've created [this](https://github.com/yegor256/cactoos/issues/1677)

**Comment by h1alexbel** [comment]
@l3r8yJ #157

**Comment by 0pdd** [comment]
The puzzle `141-51feecdd` has disappeared from the source code, that's why I closed this issue.
