### ISSUE TITLE
Version 0.0.2

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#171]

**Comment by l3r8yJ** [comment]
@h1alexbel what issues must we close for the `0.0.2` release?

**Comment by h1alexbel** [comment]
@l3r8yJ : #155, #147, and try test consumer for message consumption

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.2`

**Comment by h1alexbel** [comment]
@l3r8yJ you too!
