### ISSUE TITLE
EO way to send a message

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#180]
https://github.com/eo-cqrs/eo-kafka/blob/989e47459ac06f26698562dc3eb679ae1e1f5014/README.md?plain=1#L96

that if we instead introduce something like this, just the concept of the solution:

```java
public interface KafkaAction<? extends T> {
  T act();
}

public class KfProducerSendMessage<? extends T> implements KafkaAction<? extends T> {
  private final Producer origin;
  private final KfData<T> origin; 

  @Override
  public T act() {
    //try catch block from reference
  }
}
```
@h1alexbel wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ looks interesting!

**Comment by l3r8yJ** [comment]
I went a little deeper, the implementation actually looks like a non-oop approach with data outward. I think we should close this
