### ISSUE TITLE
version 0.1.3

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#181]

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#183](https://github.com/eo-cqrs/eo-kafka/issues/183) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#183](https://github.com/eo-cqrs/eo-kafka/issues/183) is solved here.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.1.2`

**Comment by l3r8yJ** [comment]
@h1alexbel so, let's release?

**Comment by h1alexbel** [comment]
@l3r8yJ lets go

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.1.3`
