### ISSUE TITLE
pdd

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#2]

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#19](https://github.com/eo-cqrs/eo-kafka/issues/19) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#21](https://github.com/eo-cqrs/eo-kafka/issues/21) is still not solved; solved: [#19](https://github.com/eo-cqrs/eo-kafka/issues/19).

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#21](https://github.com/eo-cqrs/eo-kafka/issues/21), [#23](https://github.com/eo-cqrs/eo-kafka/issues/23) are still not solved; solved: [#19](https://github.com/eo-cqrs/eo-kafka/issues/19).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#30](https://github.com/eo-cqrs/eo-kafka/issues/30) is still not solved; solved: [#19](https://github.com/eo-cqrs/eo-kafka/issues/19), [#21](https://github.com/eo-cqrs/eo-kafka/issues/21), [#23](https://github.com/eo-cqrs/eo-kafka/issues/23).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#39](https://github.com/eo-cqrs/eo-kafka/issues/39) is still not solved; solved: [#19](https://github.com/eo-cqrs/eo-kafka/issues/19), [#21](https://github.com/eo-cqrs/eo-kafka/issues/21), [#23](https://github.com/eo-cqrs/eo-kafka/issues/23), [#30](https://github.com/eo-cqrs/eo-kafka/issues/30).

**Comment by 0pdd** [comment]
@h1alexbel all 5 puzzles are solved here: [#19](https://github.com/eo-cqrs/eo-kafka/issues/19), [#21](https://github.com/eo-cqrs/eo-kafka/issues/21), [#23](https://github.com/eo-cqrs/eo-kafka/issues/23), [#30](https://github.com/eo-cqrs/eo-kafka/issues/30), [#39](https://github.com/eo-cqrs/eo-kafka/issues/39).
