### ISSUE TITLE
KfCallback - Producer with Callback implementation

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#204]

**Comment by l3r8yJ** [comment]
@h1alexbel i'll take it

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#265](https://github.com/eo-cqrs/eo-kafka/issues/265), [#266](https://github.com/eo-cqrs/eo-kafka/issues/266) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#265](https://github.com/eo-cqrs/eo-kafka/issues/265) is still not solved; solved: [#266](https://github.com/eo-cqrs/eo-kafka/issues/266).

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#265](https://github.com/eo-cqrs/eo-kafka/issues/265), [#266](https://github.com/eo-cqrs/eo-kafka/issues/266) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#266](https://github.com/eo-cqrs/eo-kafka/issues/266) is still not solved; solved: [#265](https://github.com/eo-cqrs/eo-kafka/issues/265).

**Comment by 0pdd** [comment]
@h1alexbel all 2 puzzles are solved here: [#265](https://github.com/eo-cqrs/eo-kafka/issues/265), [#266](https://github.com/eo-cqrs/eo-kafka/issues/266).
