### ISSUE TITLE
checkstyle-suppressions.xml:26: Turn on JavaDoc...

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#231]
The puzzle `149-79199a8c` from #149 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/6d0ef75fb720abe113f88f1366eb2767be63e3e1/checkstyle-suppressions.xml#L26-L26

The puzzle was created by @l3r8yJ on 02-Apr-23. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@l3r8yJ are we ready for now?

**Comment by l3r8yJ** [comment]
@h1alexbel I think not, as long as the configuration contains these lines:

- https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/checkstyle-suppressions.xml#L33

- https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/checkstyle-suppressions.xml#L34

- https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/checkstyle-suppressions.xml#L35

I think it makes sense to create a isse for each of them, then delete one after the other and fix all the checkstyle warnings

**Comment by h1alexbel** [comment]
@l3r8yJ yes, I agree. Can you create them?

**Comment by l3r8yJ** [comment]
@h1alexbel sure

**Comment by h1alexbel** [comment]
@l3r8yJ thanks

**Comment by 0pdd** [comment]
The puzzle `149-79199a8c` has disappeared from the source code, that's why I closed this issue.
