### ISSUE TITLE
EntryTest.java:54-56: Tests to produce-consume data....

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#236]
The puzzle `81-60413ccb` from #81 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/d5135f5697fcaf3d2e442dd79874afd06a5a1c76/src/it/producer-consumer-api/src/test/java/EntryTest.java#L54-L56

The puzzle was created by @l3r8yJ on 06-Apr-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@l3r8yJ 0.1.3

**Comment by h1alexbel** [comment]
```[Producer clientId=producer-1] Error while fetching metadata with correlation id 1 : {TEST-TOPIC=LEADER_NOT_AVAILABLE}
```

**Comment by l3r8yJ** [comment]
@h1alexbel yes, it's from #81, still don't know what's wrong

**Comment by h1alexbel** [comment]
I'm investigating what's wrong with producer

**Comment by h1alexbel** [comment]
I bet it's a network problem

**Comment by h1alexbel** [comment]
@l3r8yJ problem gone

<img width="697" alt="image" src="https://user-images.githubusercontent.com/83453843/235964019-1056290b-98aa-40ba-a209-d74a02f0c649.png">

**Comment by l3r8yJ** [comment]
@h1alexbel nice!

**Comment by h1alexbel** [comment]
@l3r8yJ our API has few bugs, I tested all of the stuff on vanilla Kafka API, succeeded.
For now I can submit it with vanilla API and create a ticket to refactor it with EO-Kafka API

**Comment by l3r8yJ** [comment]
@h1alexbel sure, we need to fix them all, waiting to your puzzles

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#287](https://github.com/eo-cqrs/eo-kafka/issues/287), [#288](https://github.com/eo-cqrs/eo-kafka/issues/288), [#289](https://github.com/eo-cqrs/eo-kafka/issues/289), [#290](https://github.com/eo-cqrs/eo-kafka/issues/290) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#304](https://github.com/eo-cqrs/eo-kafka/issues/304), [#305](https://github.com/eo-cqrs/eo-kafka/issues/305), [#306](https://github.com/eo-cqrs/eo-kafka/issues/306) are still not solved; solved: [#287](https://github.com/eo-cqrs/eo-kafka/issues/287), [#288](https://github.com/eo-cqrs/eo-kafka/issues/288), [#289](https://github.com/eo-cqrs/eo-kafka/issues/289), [#290](https://github.com/eo-cqrs/eo-kafka/issues/290).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#304](https://github.com/eo-cqrs/eo-kafka/issues/304), [#306](https://github.com/eo-cqrs/eo-kafka/issues/306) are still not solved; solved: [#287](https://github.com/eo-cqrs/eo-kafka/issues/287), [#288](https://github.com/eo-cqrs/eo-kafka/issues/288), [#289](https://github.com/eo-cqrs/eo-kafka/issues/289), [#290](https://github.com/eo-cqrs/eo-kafka/issues/290), [#305](https://github.com/eo-cqrs/eo-kafka/issues/305).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#304](https://github.com/eo-cqrs/eo-kafka/issues/304) is still not solved; solved: [#287](https://github.com/eo-cqrs/eo-kafka/issues/287), [#288](https://github.com/eo-cqrs/eo-kafka/issues/288), [#289](https://github.com/eo-cqrs/eo-kafka/issues/289), [#290](https://github.com/eo-cqrs/eo-kafka/issues/290), [#305](https://github.com/eo-cqrs/eo-kafka/issues/305), [#306](https://github.com/eo-cqrs/eo-kafka/issues/306).

**Comment by 0pdd** [comment]
@0pdd all 7 puzzles are solved here: [#287](https://github.com/eo-cqrs/eo-kafka/issues/287), [#288](https://github.com/eo-cqrs/eo-kafka/issues/288), [#289](https://github.com/eo-cqrs/eo-kafka/issues/289), [#290](https://github.com/eo-cqrs/eo-kafka/issues/290), [#304](https://github.com/eo-cqrs/eo-kafka/issues/304), [#305](https://github.com/eo-cqrs/eo-kafka/issues/305), [#306](https://github.com/eo-cqrs/eo-kafka/issues/306).
