### ISSUE TITLE
JavadocType fix

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#244]
remove this:

https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/checkstyle-suppressions.xml#L33

and fix all warnings until the build is successful

part of #231 

@h1alexbel set milestone please

**Comment by NikiTuz18** [comment]
I would like to do this

**Comment by l3r8yJ** [comment]
@NikiTuz18 sure, go ahead

**Comment by NikiTuz18** [comment]
@l3r8yJ or @h1alexbel, you can advise me about this todo's in "FkConsumer.java" and "FkProducer.java":
`/**
 * @todo #49:45m/DEV Fake Consumer implementation
 */`
`/**
 * @todo #10:45m/DEV Fake Producer implementation
 */`

They prevent maven install. Can I remove this todo's tags?

**Comment by NikiTuz18** [comment]
There is one more point. During the build, an error occurs, in my opinion, unrelated to the documentation: 
_"[ERROR] src\main\java\io\github\eocqrs\kafka\parameters\KfFlexibleEnvelope.java:[46,23] (design) VisibilityModifier: Variable 'settings' must be private and have accessor m
ethods._
"

**Comment by l3r8yJ** [comment]
> @l3r8yJ or @h1alexbel, you can advise me about this todo's in "FkConsumer.java" and "FkProducer.java":
> 
> ```
> /**
>  * @todo #49:45m/DEV Fake Consumer implementation
>  */
> /**
>  * @todo #10:45m/DEV Fake Producer implementation
>  */
> 
> [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[42,4] (javadoc) JavadocType: Unknown tag 'todo'.
> [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[38,4] (javadoc) JavadocType: Unknown tag 'todo'._
> ```
> 
> They prevent maven install. Can I remove this todo's tags?

@NikiTuz18 you just need to remove the first character `*` and it should pass, i.e:
```
/*
 * @todo #10:45m/DEV Fake Producer implementation
 */
 ```

**Comment by l3r8yJ** [comment]
> There is one more point. During the build, an error occurs, in my opinion, unrelated to the documentation: `[ERROR] src\main\java\io\github\eocqrs\kafka\parameters\KfFlexibleEnvelope.java:[46,23] (design) VisibilityModifier: Variable 'settings' must be private and have accessor methods.`

@NikiTuz18 simply fix the existing suppression for this rule in `checkstyle-suppressions.xml`

**Comment by NikiTuz18** [comment]
> > @l3r8yJ or @h1alexbel, you can advise me about this todo's in "FkConsumer.java" and "FkProducer.java":
> > ```
> > /**
> >  * @todo #49:45m/DEV Fake Consumer implementation
> >  */
> > /**
> >  * @todo #10:45m/DEV Fake Producer implementation
> >  */
> > 
> > [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[42,4] (javadoc) JavadocType: Unknown tag 'todo'.
> > [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[38,4] (javadoc) JavadocType: Unknown tag 'todo'._
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > They prevent maven install. Can I remove this todo's tags?
> 
> @NikiTuz18 you just need to remove the first character `*` and it should pass, i.e:
> 
> ```
> /*
>  * @todo #10:45m/DEV Fake Producer implementation
>  */
> ```

@l3r8yJ If do this that give a another error:
_[ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[43] (javadoc) JavadocType: Missing a Javadoc comment.
[ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[39] (javadoc) JavadocType: Missing a Javadoc comment._

**Comment by NikiTuz18** [comment]
> 

Done, it's fixed

**Comment by h1alexbel** [comment]
check out [this](
https://github.com/eo-cqrs/eo-kafka/blob/25c2ea4a7a80dcc37ae23b70c1216b17265d2b20/src/test/java/io/github/eocqrs/kafka/producer/KfProducerTest.java#L37-L46)

**Comment by NikiTuz18** [comment]
> > There is one more point. During the build, an error occurs, in my opinion, unrelated to the documentation: `[ERROR] src\main\java\io\github\eocqrs\kafka\parameters\KfFlexibleEnvelope.java:[46,23] (design) VisibilityModifier: Variable 'settings' must be private and have accessor methods.`
> 
> @NikiTuz18 simply fix the existing suppression for this rule in `checkstyle-suppressions.xml`

Done, it's fixed

**Comment by h1alexbel** [comment]
@NikiTuz18, great! 
please submit pull request

**Comment by NikiTuz18** [comment]
> @NikiTuz18, great! please submit pull request

That's not all, i need to fix it:

> > > @l3r8yJ or @h1alexbel, you can advise me about this todo's in "FkConsumer.java" and "FkProducer.java":
> > > ```
> > > /**
> > >  * @todo #49:45m/DEV Fake Consumer implementation
> > >  */
> > > /**
> > >  * @todo #10:45m/DEV Fake Producer implementation
> > >  */
> > > 
> > > [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[42,4] (javadoc) JavadocType: Unknown tag 'todo'.
> > > [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[38,4] (javadoc) JavadocType: Unknown tag 'todo'._
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > They prevent maven install. Can I remove this todo's tags?
> > 
> > 
> > @NikiTuz18 you just need to remove the first character `*` and it should pass, i.e:
> > ```
> > /*
> >  * @todo #10:45m/DEV Fake Producer implementation
> >  */
> > ```
> 
> @l3r8yJ If do this that give a another error: _[ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[43] (javadoc) JavadocType: Missing a Javadoc comment. [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[39] (javadoc) JavadocType: Missing a Javadoc comment._

**Comment by NikiTuz18** [comment]
> > @NikiTuz18, great! please submit pull request
> 
> That's not all, i need to fix it:
> 
> > > > @l3r8yJ or @h1alexbel, you can advise me about this todo's in "FkConsumer.java" and "FkProducer.java":
> > > > ```
> > > > /**
> > > >  * @todo #49:45m/DEV Fake Consumer implementation
> > > >  */
> > > > /**
> > > >  * @todo #10:45m/DEV Fake Producer implementation
> > > >  */
> > > > 
> > > > [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[42,4] (javadoc) JavadocType: Unknown tag 'todo'.
> > > > [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[38,4] (javadoc) JavadocType: Unknown tag 'todo'._
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > They prevent maven install. Can I remove this todo's tags?
> > > 
> > > 
> > > @NikiTuz18 you just need to remove the first character `*` and it should pass, i.e:
> > > ```
> > > /*
> > >  * @todo #10:45m/DEV Fake Producer implementation
> > >  */
> > > ```
> > 
> > 
> > @l3r8yJ If do this that give a another error: _[ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkConsumer.java:[43] (javadoc) JavadocType: Missing a Javadoc comment. [ERROR] src\main\java\io\github\eocqrs\kafka\fake\FkProducer.java:[39] (javadoc) JavadocType: Missing a Javadoc comment._

I can remove comment's with todo

**Comment by h1alexbel** [comment]
@NikiTuz18 don't remove it, we need those tickets to be in code for now
