### ISSUE TITLE
JavadocVariable fix

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#245]
remove this:

https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/checkstyle-suppressions.xml#L34

and fix all warnings until the build is successful

part of #231 

@h1alexbel set milestone please

**Comment by NikiTuz18** [comment]
Can I take it on?

**Comment by h1alexbel** [comment]
@NikiTuz18 sure

**Comment by NikiTuz18** [comment]
@h1alexbel I have a question. What is meant by a node in the file: _TextXpath.java_ ?
--> `private final String node;` <--

**Comment by h1alexbel** [comment]
@NikiTuz18 XML element that xpath belongs to

**Comment by l3r8yJ** [comment]
@NikiTuz18 you can provide a link to a piece of code by clicking `copy permalink`

![image](https://user-images.githubusercontent.com/46355873/230791536-86b8e095-8dcf-4c02-9c8e-30bf2c61f983.png)

and it's will look like:
https://github.com/eo-cqrs/eo-kafka/blob/00bef04f4a85f6916cccbb525898058efd587da1/src/main/java/io/github/eocqrs/kafka/xml/TextXpath.java#L36

**Comment by NikiTuz18** [comment]
@h1alexbel thaks for the answer

**Comment by l3r8yJ** [comment]
@NikiTuz18 what is the status of this issue?

**Comment by NikiTuz18** [comment]
@l3r8yJ this issue close

**Comment by l3r8yJ** [comment]
@NikiTuz18 where is the pull request where this issue was closed?

**Comment by NikiTuz18** [comment]
I have already submitted a pull request(#254), he is merge and closed
