### ISSUE TITLE
JavadocMethod fix

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#246]
remove this:

https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/checkstyle-suppressions.xml#L35

and fix all warnings until the build is successful

part of #231 

@h1alexbel set milestone please

**Comment by NikiTuz18** [comment]
I would like do it

**Comment by l3r8yJ** [comment]
@NikiTuz18 sure, go ahead
