### ISSUE TITLE
The problem of coupled tests

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#247]
I just realised that we have a big problem in tests

For example, here we using to concrete implementation of `KfAttrEnvelope` – `GroupId`:
https://github.com/eo-cqrs/eo-kafka/blob/26e54d848913812f8365a832b5c4c84d71fc5df6/src/test/java/io/github/eocqrs/kafka/consumer/settings/KfConsumerParamsTest.java#L45
Suppose we have some problem with `GroupId` that is not caught by the tests for `GroupId`. 

We use it in `KfConsumerParamsTest` and see errors. We try to find a non-existent error inside `KfConsumerParams`. To fix it, we spend a lot of time looking for the error in a class that doesn't contain it. Instead of looking for the problem at the root of the error.

I think we should use `mocks` to avoid these problems. I suggest that we start fixing our tests with [Mockito](https://github.com/mockito/mockito).

@h1alexbel wdyt

**Comment by l3r8yJ** [comment]
I will provide a pull request later with an example of how to fix this

**Comment by h1alexbel** [comment]
@l3r8yJ why we need mocks for params?

**Comment by h1alexbel** [comment]
@l3r8yJ I think we can build fake objects instead of using mocking frameworks that can turn our code into mess

WDYT

**Comment by l3r8yJ** [comment]
@h1alexbel I think the `fake-objects` approach is more suitable for user side integration/unit testing. Since tests require a complete replacement of the real API.

For internal unit tests, I would prefer to use the `mock` approach as it allows me to replace a small part of my API for my specific case in my specific test. With the `fake-objects` approach, I would instead have to completely fake object behavior for each test, instead of replacing one particular method, which seems like over-engineering to me.

I might also note that the `fake-objects` approach might be heavy, due to the fact that we need to completely replace the real API, which in itself might contradict the philosophy of unit tests. The point of unit tests is that they are very fast. Replacing the behaviour of 1 method seems to be faster than replacing the whole API

wdyt

**Comment by h1alexbel** [comment]
@l3r8yJ sounds reasonable, I think mocking is good for now

**Comment by h1alexbel** [comment]
@zoeself register.

**Comment by zoeself** [comment]
> @zoeself register.

@h1alexbel I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@h1alexbel I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by h1alexbel** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register 

@h1alexbel this issue is already registered as a task.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-04-19T05:10:11.049470``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ sory, just experimenting with new pm

**Comment by h1alexbel** [comment]
@zoeself unregister

**Comment by zoeself** [comment]
> @zoeself unregister


@h1alexbel this issue is already registered as a task.

**Comment by l3r8yJ** [comment]
@h1alexbel I tried it once, and I like using `0pdd` better, but if it is good for you, keep experimenting

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
