### ISSUE TITLE
Producer.java:28-30: Make send return CompletableFuture....

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#265]
The puzzle `204-52513c71` from #204 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/3aa29855a785b99b9631f982795880fde8a4b5d4/src/main/java/io/github/eocqrs/kafka/Producer.java#L28-L30

The puzzle was created by @l3r8yJ on 23-Apr-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-03T16:32:17.188286``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ did you mean create another method with `Future` type returned or replace current `void` implementation with new one powered with `Future`?

**Comment by h1alexbel** [comment]
also, if we will support both, `void` and `Future` we can create another interface and call it like `CallableProducer`

@l3r8yJ WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel just replace current `void` with `Future`, `void` type is a bottleneck compared to Kafka API

about `CallableProducer` for compatibility with the original Kafka API seems overthought to me

@h1alexbel wdyt

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
