### ISSUE TITLE
KfCallback.java:35-36: Integration test for `KfCallback`...

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#266]
The puzzle `204-5fca8491` from #204 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/3aa29855a785b99b9631f982795880fde8a4b5d4/src/main/java/io/github/eocqrs/kafka/producer/KfCallback.java#L35-L36

The puzzle was created by @l3r8yJ on 23-Apr-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-03T16:32:20.250693``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by 0pdd** [comment]
The puzzle `204-5fca8491` has disappeared from the source code, that's why I closed this issue.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by zoeself** [comment]
@0pdd thanks for reopening this, I'll find someone to take a look at it. 
However, please keep in mind that reopening tickets is a bad practice. Next time, please open a new ticket.

**Comment by 0pdd** [comment]
> @0pdd thanks for reopening this, I'll find someone to take a look at it. However, please keep in min...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by h1alexbel** [comment]
@l3r8yJ I can also took this one

**Comment by l3r8yJ** [comment]
@h1alexbel didn't see your message : 0, see #276

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
