### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#268]
https://github.com/eo-cqrs/eo-kafka/blob/fa6dbd43ba3e3762ff102ca14c99178043af506f/README.md?plain=1#L99-L102

Shouldn't we create a consumer/producer as follows?

```java
 final Producer<String, String> producer =
   new KfProducer<>(new KfXmlFlexible<String, String>("producer.xml"));
```

Without calling `settings#producer/consumer`

@h1alexbel wdyt

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-04T12:32:18.117727``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ yes, we can, it's just shows API variety

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
