### ISSUE TITLE
API publicity level

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#269]
I think we should hide all API members like `TextXpath` etc. Such classes should be hidden for users of our library, because they are just proprietary classes and can be misused outside our library. Also, the openness of such classes obliges us to maintain their current implementation, since the use by users of such classes forces us to make changes to them with backward compatibility support. This in turn causes a lot of problems

@h1alexbel wdyt

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-04T14:32:18.387445``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ yes, sure, go ahead

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
