### ISSUE TITLE
Clarification for whole idea

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#28]
@h1alexbel could you give me a list of the resources you need to study to help you with this project?

**Comment by h1alexbel** [comment]
@l3r8yJ yes, sure.
I recommend to start from this:

https://youtu.be/Ch5VhJzaoaI
https://www.google.com/url?sa=t&source=web&rct=j&url=https://medium.com/%40rinu.gour123/kafka-for-beginners-74ec101bc82d&ved=2ahUKEwjH1bHvrqj9AhXkhP0HHWx5CicQFnoECAgQAQ&usg=AOvVaw0YIvzpf7ICDLj8kSxJdq3a
https://www.google.com/url?sa=t&source=web&rct=j&url=https://medium.com/inspiredbrilliance/kafka-basics-and-core-concepts-5fd7a68c3193&ved=2ahUKEwjH1bHvrqj9AhXkhP0HHWx5CicQFnoECCwQAQ&usg=AOvVaw3biak2WuYx67Q4IXM6Lifx
https://medium.com/swlh/apache-kafka-what-is-and-how-it-works-e176ab31fcd5
https://www.baeldung.com/spring-kafka

**Comment by h1alexbel** [comment]
@l3r8yJ also, will be cool if you help me with building pipeline for publishing on ```Maven central```, #5
