### ISSUE TITLE
YamlFlexible

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#284]

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-13T06:22:17.182436``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ we can create consumers and producers using yaml with specs.

WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel looks interesting, you can assign it to me

**Comment by h1alexbel** [comment]
@l3r8yJ ok, I will provide my thoughts on formatting of yaml specs

**Comment by h1alexbel** [comment]
@l3r8yJ 
```
kind: Producer
spec:
  bootstrapServers: <>
  keySerializer: <>
  valueSerializer: <>
  ...
---
kind: Consumer
spec:
  bootstrapServers: <>
  groupId: <>
  keyDeserializer: <>
  valueDeserializer: <>
  ...
  ```
  All yaml attributes are formatted like in XML version

**Comment by h1alexbel** [comment]
I think we can add another method to all the `ParamAttr`

**Comment by l3r8yJ** [comment]
@h1alexbel yes, it looks like it should be

**Comment by zoeself** [comment]
@l3r8yJ Don't forget to close this ticket before the deadline (2023-05-13T06:22:17). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@l3r8yJ Looks like you've missed the task deadline (2023-05-13T06:22:17). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-23T06:42:30.421827``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2023-05-23T06:42:30). You are past the first half of the allowed period.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by h1alexbel** [comment]
@l3r8yJ idea of adding new YAML configuration lang:
users will create something like this:
```yaml
kind: Producer
spec:
  bootstrapServers: test
  keySerializer: test
  valueSerializer: test
```
then we on our side will transform this YAML document into something like this 
```yaml
producer:
  bootstrapServers: test
  keySerializer: test
  valueSerializer: test
```
And, only then, transform it into XML template, that we are [supporting](https://github.com/eo-cqrs/eo-kafka#config-api)

XML output:

```xml
<producer>
  <bootstrapServers>test</bootstrapServers>
  <keySerializer>test</keySerializer>
  <valueSerializer>test</valueSerializer>
</producer>
```

```java
public final class Yacoment<K, X> extends KfFlexibleEnvelope<K, X> {

  public Yacoment(final String name) throws Exception {
    super(name);
  }

  @Override
  public KafkaConsumer<K, X> consumer() {
    // name.yaml -> transformed.yaml -> name.xml
    // return new KfXmlFlexible<>("name.xml").consumer();
  }

  @Override
  public KafkaProducer<K, X> producer() {
    throw new UnsupportedOperationException("#producer()");
  }
}

```

WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel As far as I understand in the yaml world it is common to use `key-names-like-this`

**Comment by h1alexbel** [comment]
@l3r8yJ we can transform kebab cased yaml into yaml with camel case syntax

**Comment by h1alexbel** [comment]
```java
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.nodes.Node;
import org.yaml.snakeyaml.nodes.NodeTuple;
import org.yaml.snakeyaml.nodes.Tag;
import org.yaml.snakeyaml.representer.BaseRepresenter;
import org.yaml.snakeyaml.representer.Represent;

import java.util.Map;

public class YamlTransformation {
    public static void main(String[] args) {
        String inputYaml = "kind: Producer\n" +
                "spec:\n" +
                "  bootstrapServers: test\n" +
                "  keySerializer: test\n" +
                "  valueSerializer: test";

        // Parse the input YAML document
        Yaml yaml = new Yaml();
        Map<String, Object> data = yaml.load(inputYaml);

        // Create a custom representer to transform the data
        yaml.setRepresenter(new CustomRepresenter());

        // Convert the transformed data to YAML
        String outputYaml = yaml.dump(data);

        // Print the transformed YAML document
        System.out.println(outputYaml);
    }

    static class CustomRepresenter extends BaseRepresenter {
        @Override
        protected NodeTuple representJavaBeanProperty(Object javaBean, Property property, Object propertyValue, Tag customTag) {
            if (propertyValue instanceof Map && propertyValue != null) {
                NodeTuple defaultNodeTuple = super.representJavaBeanProperty(javaBean, property, propertyValue, customTag);
                return new NodeTuple(representData(property.getName()), defaultNodeTuple.getValueNode());
            }
            return super.representJavaBeanProperty(javaBean, property, propertyValue, customTag);
        }
    }
}
```

this code is generated by ChatGPT, I think it's time to introduce new elegant YAML transformations library/standard like XSLT

@l3r8yJ WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel honestly, the code provided by ChatGPT looks a bit ugly and procedural, I think we can take a look at [tojos](https://github.com/yegor256/tojos) and do something using it

**Comment by h1alexbel** [comment]
@l3r8yJ fully agree, this snippet is just for demonstration purposes

**Comment by l3r8yJ** [comment]
@h1alexbel see [this](https://github.com/yegor256/tojos/blob/master/src/main/java/com/yegor256/tojos/MnYaml.java)

**Comment by h1alexbel** [comment]
@l3r8yJ we can try

**Comment by h1alexbel** [comment]
I've tried [eo-yaml](https://github.com/decorators-squad/eo-yaml) already, not rich api enough for us, since we need to search values by keys in a nested way

also, it seems that tojos are not working with YAML format properly, each time I getting a `ClassCastException` inside the tojos

@l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel you can reproduce this bug with test and send a pull request to tojos, wdyt

**Comment by h1alexbel** [comment]
bug submitted https://github.com/yegor256/tojos/issues/66
