### ISSUE TITLE
test ping

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#299]

**Comment by h1alexbel** [comment]
@rultor hello

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by h1alexbel** [comment]
@rultor status

**Comment by h1alexbel** [comment]
@rultor stop
