### ISSUE TITLE
Producer.java:29: Producer send is not flexible enough

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#304]
The puzzle `287-f527de84` from #287 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/9279eec8e503156b5b7c1a05caa0f6b231a0bdee/src/main/java/io/github/eocqrs/kafka/Producer.java#L29-L29

The puzzle was created by @rultor on 08-May-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-18T13:32:17.684823``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ sure, we're accepting `KfData` object with partition, message, and topic.

But we should send message with at least value and topic. Besides that with headers, key, and etc.

**Comment by l3r8yJ** [comment]
@h1alexbel is a good idea, but maybe we should implement the message headers first?

**Comment by h1alexbel** [comment]
@l3r8yJ yes, we can do it

but, to send a message with a headers require us to pass another argument into the origin `send` method

**Comment by zoeself** [comment]
@l3r8yJ Don't forget to close this ticket before the deadline (2023-05-18T13:32:18). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@l3r8yJ Looks like you've missed the task deadline (2023-05-18T13:32:18). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-28T13:42:27.863559``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by h1alexbel** [comment]
this logic will be implemented after #194 

cc @l3r8yJ

**Comment by h1alexbel** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register

@h1alexbel I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-07-08T15:19:04.154725``.

Estimation here is ``90 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by h1alexbel** [comment]
@zoeself register

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-07-08T15:29:10.516529``.

Estimation here is ``90 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
