### ISSUE TITLE
KfConsumer.java:86-87: ConsumerRecords wrapping up we...

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#305]
The puzzle `289-af1a45bc` from #289 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/9279eec8e503156b5b7c1a05caa0f6b231a0bdee/src/main/java/io/github/eocqrs/kafka/consumer/KfConsumer.java#L86-L87

The puzzle was created by @rultor on 08-May-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-18T13:32:21.104561``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@l3r8yJ Don't forget to close this ticket before the deadline (2023-05-18T13:32:21). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@l3r8yJ Looks like you've missed the task deadline (2023-05-18T13:32:21). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-28T13:42:30.725648``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
not planned yet, since the message will be the same as in original Kafka clients api

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
