### ISSUE TITLE
kafka streams operations interface

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#329]
declare the interface for all Kafka Streams operations

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-05-29T11:52:18.062966``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@l3r8yJ Don't forget to close this ticket before the deadline (2023-05-29T11:52:18). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@l3r8yJ Looks like you've missed the task deadline (2023-05-29T11:52:18). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-06-08T12:12:21.314927``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2023-06-08T12:12:21). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@h1alexbel Looks like you've missed the task deadline (2023-06-08T12:12:21). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by zoeself** [comment]
@h1alexbel I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by h1alexbel** [comment]
check #382
