### ISSUE TITLE
Kafka Shutdown Hook

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#356]
implement abstraction over Shutdown Hook for safe Consumer shutdown management

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister


@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by h1alexbel** [comment]
due to the untestability of this logic, for now we skip implementation of shutdown hook
