### ISSUE TITLE
creation of fake topic subscription is not implemented

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#370]

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
for handling fake consumer functionality, we need to create a subscription in an XML document for the topic, on which consumer subscription happen,

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2023-06-24T12:29:10). You are past the first half of the allowed period.
