### ISSUE TITLE
deletion of fake topic subscription is not implemented 

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#371]

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
for handling fake consumer functionality, we need to delete a subscription in an XML document for the topic, after consumer unsubscribes from it

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2023-06-24T12:29:14). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
