### ISSUE TITLE
move kafka-streams to another repo

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#382]

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
streams will be developed and maintained in the separate repo, see https://github.com/eo-cqrs/ideas/issues/25

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
