### ISSUE TITLE
Producer/Consumer AutoConfiguration

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/eo-kafka#416]
@h1alexbel /in

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-07-20T08:19:08.155232``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by l3r8yJ** [comment]
won't do this
