### ISSUE TITLE
pipeline to maven central

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#5]

**Comment by l3r8yJ** [comment]
@h1alexbel i'll take it

**Comment by h1alexbel** [comment]
@l3r8yJ ok, can you write to the repository?

**Comment by l3r8yJ** [comment]
@h1alexbel no, but I don't think it's necessary, I can do through forks

**Comment by l3r8yJ** [comment]
@h1alexbel was wrong, i can

**Comment by h1alexbel** [comment]
> @h1alexbel I created [this](https://github.com/eo-cqrs/eo-cqrs-secrets) repo with secrets for `rultor`. Read more [here](https://www.l3r8y.ru/2023/02/22/complete-rultor-setup-guide)

btw, ```eo-kafka``` uses Java 17, maybe we need a specific docker image of rultor with preconfigured java17 and related maven version.
If we gonna use current ```rultor`` image, we'll have ```invalid target release!``` exception

**Comment by l3r8yJ** [comment]
@h1alexbel I will create our own docker image, but after `27.02.2023` until that date I am a little busy

**Comment by h1alexbel** [comment]
> @h1alexbel I will create our own docker image, but after `27.02.2023` until that date I am a little busy

ok, no problem

**Comment by l3r8yJ** [comment]
@h1alexbel Now we need to register `eo-kafka` on sonatype to publish, as far as I know

**Comment by h1alexbel** [comment]
> @h1alexbel Now we need to register `eo-kafka` on sonatype to publish, as far as I know

@l3r8yJ 
ok, for now, issue #68 has been created. Maybe I can implement this stuff tonight

**Comment by h1alexbel** [comment]
@l3r8yJ 
Decomposed into #113

**Comment by l3r8yJ** [comment]
@h1alexbel for this issue `pom.xml` must be configured
for #113 `.rultor.yml` must be configured

**Comment by h1alexbel** [comment]
@l3r8yJ 
Maybe I miss something, but pom.xml already prepared. If not, new tickets are welcomed
