### ISSUE TITLE
KfConsumer.java:47-56: Data polling example:...

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#57]
The puzzle `41-73d202c2` from #41 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/446bb9731e9486671d27b8e2651b668c62935196/src/main/java/org/eocqrs/kafka/consumer/KfConsumer.java#L47-L56

The puzzle was created by @h1alexbel on 26-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@l3r8yJ , I'm Investigated already, data needed to poll the data from broker is the following: ```timeout``` in Duration, and ```topic``` as String.

**Comment by l3r8yJ** [comment]
@h1alexbel nice, also our docker container will be ready soon. can you assign this issue to me?

**Comment by l3r8yJ** [comment]
@h1alexbel ill take this one too

**Comment by 0pdd** [comment]
The puzzle `41-73d202c2` has disappeared from the source code, that's why I closed this issue.

**Comment by h1alexbel** [comment]
@l3r8yJ this is an updated ticket: #81 
in order to render the javadocs I'm needed to edit the puzzle
