### ISSUE TITLE
KfConsumerTest.java:20: Consumer data polling Test

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#60]
The puzzle `41-a2146b71` from #41 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/446bb9731e9486671d27b8e2651b668c62935196/src/test/java/org/eocqrs/kafka/consumer/KfConsumerTest.java#L20-L20

The puzzle was created by Aliaksei Bialiauski on 26-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
can be completed after #81

**Comment by 0pdd** [comment]
The puzzle `41-a2146b71` has disappeared from the source code, that's why I closed this issue.
