### ISSUE TITLE
sonatype account

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#68]

**Comment by h1alexbel** [comment]
![image](https://user-images.githubusercontent.com/83453843/221757968-9b38a023-391b-47f5-ab92-d3f71d2e296b.png)

**Comment by h1alexbel** [comment]
![image](https://user-images.githubusercontent.com/83453843/221763277-39b03a86-4552-48f1-a036-232307982716.png)
@l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel nice, i'll configure rultor a bit later!
