### ISSUE TITLE
Consumer construction variety

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-kafka#92]
Consumer can be constructed from not only ```KafkaConsumer```, but also from directly XML or ```ConsumerSettings```

**Comment by l3r8yJ** [comment]
@h1alexbel i think good solution here it's [envelope](https://www.yegor256.com/2017/01/31/decorating-envelopes.html) thing or something like that

**Comment by h1alexbel** [comment]
@l3r8yJ I start investigating
