### ISSUE TITLE
KfProducerTest.java:57: Producer <> Consumer it.

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-kafka#98]
The puzzle `47-4164e46d` from #47 has to be resolved: 

https://github.com/eo-cqrs/eo-kafka/blob/af978b20c28a7a357d9c5dcae2ccdd1d1a011b7e/src/test/java/io/github/eocqrs/kafka/producer/KfProducerTest.java#L57-L57

The puzzle was created by @rultor on 08-Mar-23. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
BTW, tests should have `ITCase` suffix

**Comment by 0pdd** [comment]
The puzzle `47-4164e46d` has disappeared from the source code, that's why I closed this issue.
